const endpoints = {
  getChambers: '/getChambers',
  upsertChamber: '/upsertChamber',
  getRelays: '/getRelays',
  renameRelay: '/renameRelay',
  operateRelay: '/operateRelay',
  broadcastRelays: '/broadcastRelays',
  getSensors: '/getSensors',
  getSensorsRaw: '/getSensorsRaw',
  readEvents: '/readEvents',
  clearEvents: '/clearEvents',
  updateSensorTimeUnit: '/updateSensorTimeUnit',
  updateDetectorName: '/updateDetectorName',
  upsertSensor: '/upsertSensor',
  removeSensor: '/removeSensor',
  broadcastSensors: '/broadcastSensors',
  getActiveDevices: '/getActiveDevices',
  getSystem: '/getSystem',
  getLicenseInformation: '/getLicenseInformation',
  reboot: '/reboot',
  getWifiOptions: '/getWifiOptions',
  configureWifi: '/configureWifi',
  configureDateTime: '/configureDateTime',
  updateSystem: '/updateSystem',
  updateSoftware: '/updateSoftware',
  reset: '/reset'
}
export default endpoints;
